version: build-{branch}-#{build}

branches:
  only:
  - master
  # - develop

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      CMAKE_ARCH: x64
      CONFIG: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      CMAKE_ARCH: x64
      CMAKE_TOOLKIT: ClangCl
      CONFIG: Release

build_script:
  - mkdir build
  - cd build
  - echo "CMake configuration: %GENERATOR% %CMAKE_ARCH% %CMAKE_TOOLKIT%"
  - cmake "-G%GENERATOR%" "-A%CMAKE_ARCH%" "-T%CMAKE_TOOLKIT%" -DCMAKE_CXX_STANDARD=11 -DCML_BUILD_TESTING=ON ..
  - cmake --build . --config "%CONFIG%"

test_script:
  - ctest -V -C "%CONFIG%"

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# 
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
