language: cpp

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:

  - os: osx
    osx_image: xcode9.4

  - os: osx
    osx_image: xcode11.3

  - os: osx
    osx_image: xcode11.6
 
  - os: osx
    osx_image: xcode12

  - os: linux
    dist: bionic
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"

  - os: linux
    dist: bionic
    env:
      - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
      brew update;
      brew outdated cmake || brew upgrade cmake;
    fi

  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then
      eval "${MATRIX_EVAL}";
    fi

before_script:
  - mkdir build 
  - cd build

script:
  - ${CXX} --version
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCML_BUILD_TESTING:Bool=ON ..
  - cmake --build . --config Release -- -j2
  - ctest -V -C Release
