language: cpp

branches:
  only:
    - master
    - develop

matrix:
  include:

  - os: osx
    osx_image: xcode11.6
 
  - os: osx
    osx_image: xcode12.5

before_install:
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then
      eval "${MATRIX_EVAL}";
    fi

before_script:
  - mkdir build 
  - cd build

script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_STANDARD=11 -DCML_BUILD_TESTING:Bool=ON ..
  - cmake --build . --config Release -- -j2
  - ctest -V -C Release
